on: [push]
name: Azure ARM
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            # Checkout code
            - uses: actions/checkout@main

              # Log into Azure
            - uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS2 }}

              # Deploy Bicep file
            - name: deploy
              uses: azure/arm-deploy@v1
              with:
                  subscriptionId: ${{ secrets.AZURE_SUB }}
                  resourceGroupName: ${{ secrets.AZURE_RG }}
                  template: ./main.bicep
                  parameters: storageName='stg${uniqueString(resourceGroup().id)}'
                  failOnStdErr: false
